//

export const CSS_Object_Model = [
  {
    name: "CustomStateSet",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/CustomStateSet",
  },
  {
    name: "AnimationEvent",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/AnimationEvent",
  },
  {
    name: "CaretPosition",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/CaretPosition",
  },
  {
    name: "CSS",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/CSS",
  },
  {
    name: "CSSCharsetRule",
    type: "class",
    status: "normal",
    href: "",
  },
  {
    name: "CSSPropertyRule",
    type: "class",
    status: "normal",
    href: "",
  },
  {
    name: "CSSConditionRule",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/CSSConditionRule",
  },
  {
    name: "CSSCounterStyleRule",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/CSSCounterStyleRule",
  },
  {
    name: "CSSFontFaceRule",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/CSSFontFaceRule",
  },
  {
    name: "CSSFontFeatureValuesMap",
    type: "class",
    status: "normal",
    href: "",
  },
  {
    name: "CSSFontFeatureValuesRule",
    type: "class",
    status: "normal",
    href: "",
  },
  {
    name: "CSSGroupingRule",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/CSSGroupingRule",
  },
  {
    name: "CSSImportRule",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/CSSImportRule",
  },
  {
    name: "CSSKeyframeRule",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/CSSKeyframeRule",
  },
  {
    name: "CSSKeyframesRule",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/CSSKeyframesRule",
  },
  {
    name: "CSSMarginRule",
    type: "class",
    status: "normal",
    href: "",
  },
  {
    name: "CSSMediaRule",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/CSSMediaRule",
  },
  {
    name: "CSSNamespaceRule",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/CSSNamespaceRule",
  },
  {
    name: "CSSPageRule",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/CSSPageRule",
  },
  {
    name: "CSSRule",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/CSSRule",
  },
  {
    name: "CSSRuleList",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/CSSRuleList",
  },
  {
    name: "CSSStyleDeclaration",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration",
  },
  {
    name: "CSSStyleSheet",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet",
  },
  {
    name: "CSSStyleRule",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleRule",
  },
  {
    name: "CSSSupportsRule",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/CSSSupportsRule",
  },
  {
    name: "CSSVariablesMap",
    type: "class",
    status: "normal",
    href: "",
  },
  {
    name: "CSSViewportRule",
    type: "class",
    status: "normal",
    href: "",
  },
  {
    name: "FontFace",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/FontFace",
  },
  {
    name: "FontFaceSet",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/FontFaceSet",
  },
  {
    name: "FontFaceSetLoadEvent",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/FontFaceSetLoadEvent",
  },
  {
    name: "GetStyleUtils",
    type: "class",
    status: "normal",
    href: "",
  },
  {
    name: "MediaList",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/MediaList",
  },
  {
    name: "MediaQueryList",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList",
  },
  {
    name: "MediaQueryListEvent",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryListEvent",
  },
  {
    name: "Screen",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/Screen",
  },
  {
    name: "StyleSheet",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/StyleSheet",
  },
  {
    name: "StyleSheetList",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/StyleSheetList",
  },
  {
    name: "TransitionEvent",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/TransitionEvent",
  },
  {
    name: "CSSImageValue",
    type: "class",
    status: "experimental",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/CSSImageValue",
  },
  {
    name: "CSSKeywordValue",
    type: "class",
    status: "experimental",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/CSSKeywordValue",
  },
  {
    name: "CSSMathInvert",
    type: "class",
    status: "experimental",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/CSSMathInvert",
  },
  {
    name: "CSSMathMax",
    type: "class",
    status: "experimental",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/CSSMathMax",
  },
  {
    name: "CSSMathMin",
    type: "class",
    status: "experimental",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/CSSMathMin",
  },
  {
    name: "CSSMathNegate",
    type: "class",
    status: "experimental",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/CSSMathNegate",
  },
  {
    name: "CSSMathProduct",
    type: "class",
    status: "experimental",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/CSSMathProduct",
  },
  {
    name: "CSSMathSum",
    type: "class",
    status: "experimental",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/CSSMathSum",
  },
  {
    name: "CSSMathValue",
    type: "class",
    status: "experimental",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/CSSMathValue",
  },
  {
    name: "CSSMatrixComponent",
    type: "class",
    status: "experimental",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/CSSMatrixComponent",
  },
  {
    name: "CSSNumericArray",
    type: "class",
    status: "experimental",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/CSSNumericArray",
  },
  {
    name: "CSSNumericValue",
    type: "class",
    status: "experimental",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/CSSNumericValue",
  },
  {
    name: "CSSPerspective",
    type: "class",
    status: "experimental",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/CSSPerspective",
  },
  {
    name: "CSSPositionValue",
    type: "class",
    status: "experimental",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/CSSPositionValue",
  },
  {
    name: "CSSRotate",
    type: "class",
    status: "experimental",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/CSSRotate",
  },
  {
    name: "CSSScale",
    type: "class",
    status: "experimental",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/CSSScale",
  },
  {
    name: "CSSSkew",
    type: "class",
    status: "experimental",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/CSSSkew",
  },
  {
    name: "CSSSkewX",
    type: "class",
    status: "experimental",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/CSSSkewX",
  },
  {
    name: "CSSSkewY",
    type: "class",
    status: "experimental",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/CSSSkewY",
  },
  {
    name: "CSSStyleValue",
    type: "class",
    status: "experimental",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleValue",
  },
  {
    name: "CSSTransformComponent",
    type: "class",
    status: "experimental",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/CSSTransformComponent",
  },
  {
    name: "CSSTransformValue",
    type: "class",
    status: "experimental",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/CSSTransformValue",
  },
  {
    name: "CSSTranslate",
    type: "class",
    status: "experimental",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/CSSTranslate",
  },
  {
    name: "CSSUnitValue",
    type: "class",
    status: "experimental",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/CSSUnitValue",
  },
  {
    name: "CSSUnparsedValue",
    type: "class",
    status: "experimental",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/CSSUnparsedValue",
  },
  {
    name: "CSSVariableReferenceValue",
    type: "class",
    status: "experimental",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/CSSVariableReferenceValue",
  },
  {
    name: "StylePropertyMap",
    type: "class",
    status: "experimental",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/StylePropertyMap",
  },
  {
    name: "StylePropertyMapReadOnly",
    type: "class",
    status: "experimental",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/StylePropertyMapReadOnly",
  },
  {
    name: "CSSPrimitiveValue",
    type: "class",
    status: "deprecated",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/CSSPrimitiveValue",
  },
  {
    name: "CSSValue",
    type: "class",
    status: "deprecated",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/CSSValue",
  },
  {
    name: "CSSValueList",
    type: "class",
    status: "deprecated",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/CSSValueList",
  },
];
