//

const DOM = [
  { name: "StaticRange" },
  { name: "AbstractRange" },
  { name: "AbortSignal" },
  { name: "AbortController" },
  {
    name: "Attr",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/Attr",
  },
  {
    name: "CDATASection",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/CDATASection",
  },
  {
    name: "CharacterData",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/CharacterData",
  },
  {
    name: "Comment",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/Comment",
  },
  {
    name: "CustomEvent",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent",
  },
  {
    name: "Document",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/Document",
  },
  {
    name: "DocumentFragment",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment",
  },
  {
    name: "DocumentType",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/DocumentType",
  },
  {
    name: "DOMError",
    type: "class",
    status: "deprecated",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/DOMError",
  },
  {
    name: "DOMException",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/DOMException",
  },
  {
    name: "DOMImplementation",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/DOMImplementation",
  },
  {
    name: "DOMString",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/DOMString",
  },
  {
    name: "DOMTimeStamp",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/DOMTimeStamp",
  },
  {
    name: "DOMStringList",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/DOMStringList",
  },
  {
    name: "DOMTokenList",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList",
  },
  {
    name: "Element",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/Element",
  },
  {
    name: "Event",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/Event",
  },
  {
    name: "EventTarget",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/EventTarget",
  },
  {
    name: "HTMLCollection",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLCollection",
  },
  {
    name: "MutationObserver",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver",
  },
  {
    name: "MutationRecord",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/MutationRecord",
  },
  {
    name: "NamedNodeMap",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/NamedNodeMap",
  },
  {
    name: "Node",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/Node",
  },
  {
    name: "NodeFilter",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/NodeFilter",
  },
  {
    name: "NodeIterator",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/NodeIterator",
  },
  {
    name: "NodeList",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/NodeList",
  },
  {
    name: "ProcessingInstruction",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/ProcessingInstruction",
  },
  {
    name: "Selection",
    type: "class",
    status: "experimental",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/Selection",
  },
  {
    name: "Range",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/Range",
  },
  {
    name: "Text",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/Text",
  },
  {
    name: "TextDecoder",
    type: "class",
    status: "experimental",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/TextDecoder",
  },
  {
    name: "TextEncoder",
    type: "class",
    status: "experimental",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder",
  },
  {
    name: "TimeRanges",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/TimeRanges",
  },
  {
    name: "TreeWalker",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/TreeWalker",
  },
  {
    name: "URL",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/URL",
  },
  {
    name: "Window",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/Window",
  },
  {
    name: "Worker",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/Worker",
  },
  {
    name: "XMLDocument",
    type: "class",
    status: "experimental",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/XMLDocument",
  },

  {
    name: "DOMConfiguration",
    type: "class",
    status: "deprecated",
    href: "",
  },
  {
    name: "DOMErrorHandler",
    type: "class",
    status: "deprecated",
    href: "",
  },
  {
    name: "DOMImplementationList",
    type: "class",
    status: "deprecated",
    href: "",
  },
  {
    name: "DOMImplementationRegistry",
    type: "class",
    status: "deprecated",
    href: "",
  },
  {
    name: "DOMImplementationSource",
    type: "class",
    status: "deprecated",
    href: "",
  },
  {
    name: "DOMLocator",
    type: "class",
    status: "deprecated",
    href: "",
  },
  {
    name: "DOMObject",
    type: "class",
    status: "deprecated",
    href: "",
  },
  {
    name: "DOMSettableTokenList",
    type: "class",
    status: "deprecated",
    href: "",
  },
  {
    name: "DOMUserData",
    type: "class",
    status: "deprecated",
    href: "",
  },
  {
    name: "ElementTraversal",
    type: "class",
    status: "deprecated",
    href: "",
  },
  {
    name: "Entity",
    type: "class",
    status: "deprecated",
    href: "",
  },
  {
    name: "EntityReference",
    type: "class",
    status: "deprecated",
    href: "",
  },
  {
    name: "NameList",
    type: "class",
    status: "deprecated",
    href: "",
  },
  {
    name: "Notation",
    type: "class",
    status: "deprecated",
    href: "",
  },
  {
    name: "TypeInfo",
    type: "class",
    status: "deprecated",
    href: "",
  },
  {
    name: "UserDataHandler",
    type: "class",
    status: "deprecated",
    href: "",
  },
];

const SVG = [
  {
    name: "SVGAElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGAElement",
  },
  {
    name: "SVGAltGlyphElement",
    type: "class",
    status: "deprecated",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGAltGlyphElement",
  },
  {
    name: "SVGAltGlyphDefElement",
    type: "class",
    status: "deprecated",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGAltGlyphDefElement",
  },
  {
    name: "SVGAltGlyphItemElement",
    type: "class",
    status: "deprecated",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGAltGlyphItemElement",
  },
  {
    name: "SVGAnimationElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimationElement",
  },
  {
    name: "SVGAnimateElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimateElement",
  },
  {
    name: "SVGAnimateColorElement",
    type: "class",
    status: "deprecated",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimateColorElement",
  },
  {
    name: "SVGAnimateMotionElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimateMotionElement",
  },
  {
    name: "SVGAnimateTransformElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimateTransformElement",
  },
  {
    name: "SVGCircleElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGCircleElement",
  },
  {
    name: "SVGClipPathElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGClipPathElement",
  },
  {
    name: "SVGComponentTransferFunctionElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGComponentTransferFunctionElement",
  },
  {
    name: "SVGCursorElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGCursorElement",
  },
  {
    name: "SVGDefsElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGDefsElement",
  },
  {
    name: "SVGDescElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGDescElement",
  },
  {
    name: "SVGElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGElement",
  },
  {
    name: "SVGEllipseElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGEllipseElement",
  },
  {
    name: "SVGFEBlendElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGFEBlendElement",
  },
  {
    name: "SVGFEColorMatrixElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGFEColorMatrixElement",
  },
  {
    name: "SVGFEComponentTransferElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGFEComponentTransferElement",
  },
  {
    name: "SVGFECompositeElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGFECompositeElement",
  },
  {
    name: "SVGFEConvolveMatrixElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGFEConvolveMatrixElement",
  },
  {
    name: "SVGFEDiffuseLightingElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGFEDiffuseLightingElement",
  },
  {
    name: "SVGFEDisplacementMapElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGFEDisplacementMapElement",
  },
  {
    name: "SVGFEDistantLightElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGFEDistantLightElement",
  },
  {
    name: "SVGFEDropShadowElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGFEDropShadowElement",
  },
  {
    name: "SVGFEFloodElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGFEFloodElement",
  },
  {
    name: "SVGFEFuncAElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGFEFuncAElement",
  },
  {
    name: "SVGFEFuncBElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGFEFuncBElement",
  },
  {
    name: "SVGFEFuncGElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGFEFuncGElement",
  },
  {
    name: "SVGFEFuncRElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGFEFuncRElement",
  },
  {
    name: "SVGFEGaussianBlurElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGFEGaussianBlurElement",
  },
  {
    name: "SVGFEImageElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGFEImageElement",
  },
  {
    name: "SVGFEMergeElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGFEMergeElement",
  },
  {
    name: "SVGFEMergeNodeElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGFEMergeNodeElement",
  },
  {
    name: "SVGFEMorphologyElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGFEMorphologyElement",
  },
  {
    name: "SVGFEOffsetElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGFEOffsetElement",
  },
  {
    name: "SVGFEPointLightElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGFEPointLightElement",
  },
  {
    name: "SVGFESpecularLightingElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGFESpecularLightingElement",
  },
  {
    name: "SVGFESpotLightElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGFESpotLightElement",
  },
  {
    name: "SVGFETileElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGFETileElement",
  },
  {
    name: "SVGFETurbulenceElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGFETurbulenceElement",
  },
  {
    name: "SVGFilterElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGFilterElement",
  },
  {
    name: "SVGFilterPrimitiveStandardAttributes",
    type: "class",
    status: "normal",
    href: "",
  },
  {
    name: "SVGFontElement",
    type: "class",
    status: "deprecated",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGFontElement",
  },
  {
    name: "SVGFontFaceElement",
    type: "class",
    status: "deprecated",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGFontFaceElement",
  },
  {
    name: "SVGFontFaceFormatElement",
    type: "class",
    status: "deprecated",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGFontFaceFormatElement",
  },
  {
    name: "SVGFontFaceNameElement",
    type: "class",
    status: "deprecated",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGFontFaceNameElement",
  },
  {
    name: "SVGFontFaceSrcElement",
    type: "class",
    status: "deprecated",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGFontFaceSrcElement",
  },
  {
    name: "SVGFontFaceUriElement",
    type: "class",
    status: "deprecated",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGFontFaceUriElement",
  },
  {
    name: "SVGForeignObjectElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGForeignObjectElement",
  },
  {
    name: "SVGGElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGGElement",
  },
  {
    name: "SVGGeometryElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGGeometryElement",
  },
  {
    name: "SVGGlyphElement",
    type: "class",
    status: "deprecated",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGGlyphElement",
  },
  {
    name: "SVGGlyphRefElement",
    type: "class",
    status: "deprecated",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGGlyphRefElement",
  },
  {
    name: "SVGGradientElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGGradientElement",
  },
  {
    name: "SVGGraphicsElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGGraphicsElement",
  },
  {
    name: "SVGHatchElement",
    type: "class",
    status: "experimental",
    href: "",
  },
  {
    name: "SVGHatchpathElement",
    type: "class",
    status: "experimental",
    href: "",
  },
  {
    name: "SVGHKernElement",
    type: "class",
    status: "deprecated",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGHKernElement",
  },
  {
    name: "SVGImageElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGImageElement",
  },
  {
    name: "SVGLinearGradientElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGLinearGradientElement",
  },
  {
    name: "SVGLineElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGLineElement",
  },
  {
    name: "SVGMarkerElement",
    type: "class",
    status: "experimental",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGMarkerElement",
  },
  {
    name: "SVGMaskElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGMaskElement",
  },
  {
    name: "SVGMetadataElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGMetadataElement",
  },
  {
    name: "SVGMissingGlyphElement",
    type: "class",
    status: "deprecated",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGMissingGlyphElement",
  },
  {
    name: "SVGMPathElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGMPathElement",
  },
  {
    name: "SVGPathElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGPathElement",
  },
  {
    name: "SVGPatternElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGPatternElement",
  },
  {
    name: "SVGPolylineElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGPolylineElement",
  },
  {
    name: "SVGPolygonElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGPolygonElement",
  },
  {
    name: "SVGRadialGradientElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGRadialGradientElement",
  },
  {
    name: "SVGRectElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGRectElement",
  },
  {
    name: "SVGScriptElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGScriptElement",
  },
  {
    name: "SVGSetElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGSetElement",
  },
  {
    name: "SVGStopElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGStopElement",
  },
  {
    name: "SVGStyleElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGStyleElement",
  },
  {
    name: "SVGSVGElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGSVGElement",
  },
  {
    name: "SVGSwitchElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGSwitchElement",
  },
  {
    name: "SVGSymbolElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGSymbolElement",
  },
  {
    name: "SVGTextContentElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGTextContentElement",
  },
  {
    name: "SVGTextElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGTextElement",
  },
  {
    name: "SVGTextPathElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGTextPathElement",
  },
  {
    name: "SVGTextPositioningElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGTextPositioningElement",
  },
  {
    name: "SVGTitleElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGTitleElement",
  },
  {
    name: "SVGTRefElement",
    type: "class",
    status: "deprecated",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGTRefElement",
  },
  {
    name: "SVGTSpanElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGTSpanElement",
  },
  {
    name: "SVGUseElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGUseElement",
  },
  {
    name: "SVGViewElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGViewElement",
  },
  {
    name: "SVGVKernElement",
    type: "class",
    status: "deprecated",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGVKernElement",
  },

  {
    name: "SVGAngle",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGAngle",
  },
  {
    name: "SVGColor",
    type: "class",
    status: "deprecated",
    href: "",
  },
  {
    name: "SVGICCColor",
    type: "class",
    status: "deprecated",
    href: "",
  },
  {
    name: "SVGElementInstance",
    type: "class",
    status: "normal",
    href: "",
  },
  {
    name: "SVGElementInstanceList",
    type: "class",
    status: "normal",
    href: "",
  },
  {
    name: "SVGLength",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGLength",
  },
  {
    name: "SVGLengthList",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGLengthList",
  },
  {
    name: "SVGMatrix",
    type: "class",
    status: "deprecated",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGMatrix",
  },
  {
    name: "SVGNameList",
    type: "class",
    status: "normal",
    href: "",
  },
  {
    name: "SVGNumber",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGNumber",
  },
  {
    name: "SVGNumberList",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGNumberList",
  },
  {
    name: "SVGPaint",
    type: "class",
    status: "normal",
    href: "",
  },
  {
    name: "SVGPathSeg",
    type: "class",
    status: "deprecated",
    href: "",
  },
  {
    name: "SVGPathSegClosePath",
    type: "class",
    status: "deprecated",
    href: "",
  },
  {
    name: "SVGPathSegMovetoAbs",
    type: "class",
    status: "deprecated",
    href: "",
  },
  {
    name: "SVGPathSegMovetoRel",
    type: "class",
    status: "deprecated",
    href: "",
  },
  {
    name: "SVGPathSegLinetoAbs",
    type: "class",
    status: "deprecated",
    href: "",
  },
  {
    name: "SVGPathSegLinetoRel",
    type: "class",
    status: "deprecated",
    href: "",
  },
  {
    name: "SVGPathSegCurvetoCubicAbs",
    type: "class",
    status: "deprecated",
    href: "",
  },
  {
    name: "SVGPathSegCurvetoCubicRel",
    type: "class",
    status: "deprecated",
    href: "",
  },
  {
    name: "SVGPathSegCurvetoQuadraticAbs",
    type: "class",
    status: "deprecated",
    href: "",
  },
  {
    name: "SVGPathSegCurvetoQuadraticRel",
    type: "class",
    status: "deprecated",
    href: "",
  },
  {
    name: "SVGPathSegArcAbs",
    type: "class",
    status: "deprecated",
    href: "",
  },
  {
    name: "SVGPathSegArcRel",
    type: "class",
    status: "deprecated",
    href: "",
  },
  {
    name: "SVGPathSegLinetoHorizontalAbs",
    type: "class",
    status: "deprecated",
    href: "",
  },
  {
    name: "SVGPathSegLinetoHorizontalRel",
    type: "class",
    status: "deprecated",
    href: "",
  },
  {
    name: "SVGPathSegLinetoVerticalAbs",
    type: "class",
    status: "deprecated",
    href: "",
  },
  {
    name: "SVGPathSegLinetoVerticalRel",
    type: "class",
    status: "deprecated",
    href: "",
  },
  {
    name: "SVGPathSegCurvetoCubicSmoothAbs",
    type: "class",
    status: "deprecated",
    href: "",
  },
  {
    name: "SVGPathSegCurvetoCubicSmoothRel",
    type: "class",
    status: "deprecated",
    href: "",
  },
  {
    name: "SVGPathSegCurvetoQuadraticSmoothAbs",
    type: "class",
    status: "deprecated",
    href: "",
  },
  {
    name: "SVGPathSegCurvetoQuadraticSmoothRel",
    type: "class",
    status: "deprecated",
    href: "",
  },
  {
    name: "SVGPathSegList",
    type: "class",
    status: "deprecated",
    href: "",
  },
  {
    name: "SVGPoint",
    type: "class",
    status: "deprecated",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGPoint",
  },
  {
    name: "SVGPointList",
    type: "class",
    status: "deprecated",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGPointList",
  },
  {
    name: "SVGPreserveAspectRatio",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGPreserveAspectRatio",
  },
  {
    name: "SVGRect",
    type: "class",
    status: "deprecated",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGRect",
  },
  {
    name: "SVGStringList",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGStringList",
  },
  {
    name: "SVGTransform",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGTransform",
  },
  {
    name: "SVGTransformList",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGTransformList",
  },

  {
    name: "SVGAnimatedAngle",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimatedAngle",
  },
  {
    name: "SVGAnimatedBoolean",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimatedBoolean",
  },
  {
    name: "SVGAnimatedEnumeration",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimatedEnumeration",
  },
  {
    name: "SVGAnimatedInteger",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimatedInteger",
  },
  {
    name: "SVGAnimatedLength",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimatedLength",
  },
  {
    name: "SVGAnimatedLengthList",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimatedLengthList",
  },
  {
    name: "SVGAnimatedNumber",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimatedNumber",
  },
  {
    name: "SVGAnimatedNumberList",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimatedNumberList",
  },
  {
    name: "SVGAnimatedPathData",
    type: "class",
    status: "deprecated",
    href: "",
  },
  {
    name: "SVGAnimatedPoints",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGPolygonElement",
  },
  {
    name: "SVGAnimatedPreserveAspectRatio",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimatedPreserveAspectRatio",
  },
  {
    name: "SVGAnimatedRect",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimatedRect",
  },
  {
    name: "SVGAnimatedString",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimatedString",
  },
  {
    name: "SVGAnimatedTransformList",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimatedTransformList",
  },

  {
    name: "ElementTimeControl",
    type: "class",
    status: "normal",
    href: "",
  },
  {
    name: "TimeEvent",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/TimeEvent",
  },

  {
    name: "GetSVGDocument",
    type: "class",
    status: "normal",
    href: "",
  },
  {
    name: "ShadowAnimation",
    type: "class",
    status: "normal",
    href: "",
  },
  {
    name: "SVGColorProfileRule",
    type: "class",
    status: "deprecated",
    href: "",
  },
  {
    name: "SVGCSSRule",
    type: "class",
    status: "deprecated",
    href: "",
  },
  {
    name: "SVGDocument",
    type: "class",
    status: "normal",
    href: "",
  },
  {
    name: "SVGException",
    type: "class",
    status: "deprecated",
    href: "",
  },
  {
    name: "SVGFitToViewBox",
    type: "class",
    status: "normal",
    href: "",
  },
  {
    name: "SVGLocatable",
    type: "class",
    status: "deprecated",
    href: "",
  },
  {
    name: "SVGRenderingIntent",
    type: "class",
    status: "deprecated",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGRenderingIntent",
  },
  {
    name: "SVGUnitTypes",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SVGUnitTypes",
  },
  {
    name: "SVGUseElementShadowRoot",
    type: "class",
    status: "normal",
    href: "",
  },
  {
    name: "SVGViewSpec",
    type: "class",
    status: "deprecated",
    href: "",
  },
  {
    name: "SVGZoomEvent",
    type: "class",
    status: "deprecated",
    href: "",
  },
];

export const Document_Object_Model = [...DOM, ...SVG];
