//
export const HTML_DOM = [
  {
    name: "HTMLAnchorElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLAnchorElement",
  },
  {
    name: "HTMLAreaElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLAreaElement",
  },
  {
    name: "HTMLAudioElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLAudioElement",
  },
  {
    name: "HTMLBaseElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLBaseElement",
  },
  {
    name: "HTMLBodyElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLBodyElement",
  },
  {
    name: "HTMLBRElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLBRElement",
  },
  {
    name: "HTMLButtonElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLButtonElement",
  },
  {
    name: "HTMLCanvasElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement",
  },
  {
    name: "HTMLDataElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLDataElement",
  },
  {
    name: "HTMLDataListElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLDataListElement",
  },
  {
    name: "HTMLDetailsElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLDetailsElement",
  },
  {
    name: "HTMLDialogElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement",
  },
  {
    name: "HTMLDirectoryElement",
    type: "class",
    status: "normal",
    href: "",
  },
  {
    name: "HTMLDivElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLDivElement",
  },
  {
    name: "HTMLDListElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLDListElement",
  },
  {
    name: "HTMLElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement",
  },
  {
    name: "HTMLEmbedElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLEmbedElement",
  },
  {
    name: "HTMLFieldSetElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLFieldSetElement",
  },
  {
    name: "HTMLFormElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement",
  },
  {
    name: "HTMLHRElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLHRElement",
  },
  {
    name: "HTMLHeadElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLHeadElement",
  },
  {
    name: "HTMLHeadingElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLHeadingElement",
  },
  {
    name: "HTMLHtmlElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLHtmlElement",
  },
  {
    name: "HTMLIFrameElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLIFrameElement",
  },
  {
    name: "HTMLImageElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement",
  },
  {
    name: "HTMLInputElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement",
  },
  {
    name: "HTMLLabelElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLLabelElement",
  },
  {
    name: "HTMLLegendElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLLegendElement",
  },
  {
    name: "HTMLLIElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLLIElement",
  },
  {
    name: "HTMLLinkElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLLinkElement",
  },
  {
    name: "HTMLMapElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLMapElement",
  },
  {
    name: "HTMLMediaElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement",
  },
  {
    name: "HTMLMenuElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLMenuElement",
  },
  {
    name: "HTMLMetaElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLMetaElement",
  },
  {
    name: "HTMLMeterElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLMeterElement",
  },
  {
    name: "HTMLModElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLModElement",
  },
  {
    name: "HTMLObjectElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLObjectElement",
  },
  {
    name: "HTMLOListElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLOListElement",
  },
  {
    name: "HTMLOptGroupElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLOptGroupElement",
  },
  {
    name: "HTMLOptionElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLOptionElement",
  },
  {
    name: "HTMLOutputElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLOutputElement",
  },
  {
    name: "HTMLParagraphElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLParagraphElement",
  },
  {
    name: "HTMLParamElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLParamElement",
  },
  {
    name: "HTMLPictureElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLPictureElement",
  },
  {
    name: "HTMLPreElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLPreElement",
  },
  {
    name: "HTMLProgressElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLProgressElement",
  },
  {
    name: "HTMLQuoteElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLQuoteElement",
  },
  {
    name: "HTMLScriptElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLScriptElement",
  },
  {
    name: "HTMLSelectElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement",
  },
  {
    name: "HTMLSlotElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLSlotElement",
  },
  {
    name: "HTMLSourceElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLSourceElement",
  },
  {
    name: "HTMLSpanElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLSpanElement",
  },
  {
    name: "HTMLStyleElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLStyleElement",
  },
  {
    name: "HTMLTableCaptionElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLTableCaptionElement",
  },
  {
    name: "HTMLTableCellElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLTableCellElement",
  },
  {
    name: "HTMLTableColElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLTableColElement",
  },
  {
    name: "HTMLTableElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLTableElement",
  },
  {
    name: "HTMLTableRowElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLTableRowElement",
  },
  {
    name: "HTMLTableSectionElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLTableSectionElement",
  },
  {
    name: "HTMLTemplateElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLTemplateElement",
  },
  {
    name: "HTMLTextAreaElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement",
  },
  {
    name: "HTMLTimeElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLTimeElement",
  },
  {
    name: "HTMLTitleElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLTitleElement",
  },
  {
    name: "HTMLTrackElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLTrackElement",
  },
  {
    name: "HTMLUListElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLUListElement",
  },
  {
    name: "HTMLUnknownElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLUnknownElement",
  },
  {
    name: "HTMLVideoElement",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLVideoElement",
  },

  {
    name: "HTMLMarqueeElement",
    type: "class",
    status: "deprecated",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLMarqueeElement",
  },

  {
    name: "HTMLBaseFontElement",
    type: "class",
    status: "deprecated",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLBaseFontElement",
  },
  {
    name: "HTMLFontElement",
    type: "class",
    status: "deprecated",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLFontElement",
  },
  {
    name: "HTMLFrameElement",
    type: "class",
    status: "deprecated",
    href: "",
  },
  {
    name: "HTMLFrameSetElement",
    type: "class",
    status: "deprecated",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLFrameSetElement",
  },
  {
    name: "HTMLIsIndexElement",
    type: "class",
    status: "deprecated",
    href: "",
  },
  {
    name: "HTMLMenuItemElement",
    type: "class",
    status: "deprecated",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLMenuItemElement",
  },

  {
    name: "BarProp",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/BarProp",
  },
  {
    name: "Navigator",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/Navigator",
  },
  {
    name: "Window",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/Window",
  },
  {
    name: "External",
    type: "class",
    status: "deprecated",
    href: "",
  },

  {
    name: "ApplicationCache",
    type: "class",
    status: "deprecated",
    href: "",
  },
  {
    name: "Plugin",
    type: "class",
    status: "deprecated",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/Plugin",
  },
  {
    name: "PluginArray",
    type: "class",
    status: "deprecated",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/PluginArray",
  },

  {
    name: "FormDataEvent",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/FormDataEvent",
  },
  {
    name: "HTMLFormControlsCollection",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormControlsCollection",
  },
  {
    name: "HTMLOptionsCollection",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLOptionsCollection",
  },
  {
    name: "RadioNodeList",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/RadioNodeList",
  },
  {
    name: "ValidityState",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/ValidityState",
  },

  {
    name: "CanvasGradient",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/CanvasGradient",
  },
  {
    name: "CanvasPattern",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/CanvasPattern",
  },
  {
    name: "CanvasRenderingContext2D",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D",
  },
  {
    name: "ImageBitmap",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/ImageBitmap",
  },
  {
    name: "ImageBitmapRenderingContext",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/ImageBitmapRenderingContext",
  },
  {
    name: "ImageData",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/ImageData",
  },
  {
    name: "OffscreenCanvas",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas",
  },
  {
    name: "OffscreenCanvasRenderingContext2D",
    type: "class",
    status: "normal",
    href: "",
  },
  {
    name: "Path2D",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/Path2D",
  },
  {
    name: "TextMetrics",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/TextMetrics",
  },

  {
    name: "AudioTrack",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/AudioTrack",
  },
  {
    name: "AudioTrackList",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/AudioTrackList",
  },
  {
    name: "MediaError",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/MediaError",
  },
  {
    name: "TextTrack",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/TextTrack",
  },
  {
    name: "TextTrackCue",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/TextTrackCue",
  },
  {
    name: "TextTrackCueList",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/TextTrackCueList",
  },
  {
    name: "TextTrackList",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/TextTrackList",
  },
  {
    name: "TimeRanges",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/TimeRanges",
  },
  {
    name: "TrackEvent",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/TrackEvent",
  },
  {
    name: "VideoTrack",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/VideoTrack",
  },
  {
    name: "VideoTrackList",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/VideoTrackList",
  },

  {
    name: "DataTransfer",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer",
  },
  {
    name: "DataTransferItem",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/DataTransferItem",
  },
  {
    name: "DataTransferItemList",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/DataTransferItemList",
  },
  {
    name: "DragEvent",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/DragEvent",
  },

  {
    name: "BeforeUnloadEvent",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/BeforeUnloadEvent",
  },
  {
    name: "HashChangeEvent",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HashChangeEvent",
  },
  {
    name: "History",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/History",
  },
  {
    name: "Location",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/Location",
  },
  {
    name: "PageTransitionEvent",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/PageTransitionEvent",
  },
  {
    name: "PopStateEvent",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/PopStateEvent",
  },

  {
    name: "CustomElementRegistry",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry",
  },

  {
    name: "DOMStringList",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/DOMStringList",
  },
  {
    name: "DOMStringMap",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/DOMStringMap",
  },
  {
    name: "ErrorEvent",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/ErrorEvent",
  },
  {
    name: "HTMLAllCollection",
    type: "class",
    status: "normal",
    href: "",
  },
  {
    name: "MimeType",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/MimeType",
  },
  {
    name: "MimeTypeArray",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/MimeTypeArray",
  },
  {
    name: "PromiseRejectionEvent",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/PromiseRejectionEvent",
  },
];
