export const Service_Worker = [
  {
    name: "Cache",
    type: "class",
    status: "experimental",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/Cache",
  },
  {
    name: "CacheStorage",
    type: "class",
    status: "experimental",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/CacheStorage",
  },
  {
    name: "Client",
    type: "class",
    status: "experimental",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/Client",
  },
  {
    name: "Clients",
    type: "class",
    status: "experimental",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/Clients",
  },
  {
    name: "ExtendableEvent",
    type: "class",
    status: "experimental",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/ExtendableEvent",
  },
  {
    name: "ExtendableMessageEvent",
    type: "class",
    status: "experimental",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/ExtendableMessageEvent",
  },
  {
    name: "FetchEvent",
    type: "class",
    status: "experimental",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/FetchEvent",
  },
  {
    name: "InstallEvent",
    type: "class",
    status: "experimental",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/InstallEvent",
  },
  {
    name: "NavigationPreloadManager",
    type: "class",
    status: "experimental",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/NavigationPreloadManager",
  },
  {
    name: "Navigator.serviceWorker",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/Navigator/serviceWorker",
  },
  {
    name: "NotificationEvent",
    type: "class",
    status: "experimental",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/NotificationEvent",
  },
  {
    name: "ServiceWorker",
    type: "class",
    status: "experimental",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorker",
  },
  {
    name: "ServiceWorkerContainer",
    type: "class",
    status: "experimental",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerContainer",
  },
  {
    name: "ServiceWorkerGlobalScope",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerGlobalScope",
  },
  {
    name: "ServiceWorkerMessageEvent",
    type: "class",
    status: "deprecated",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerMessageEvent",
  },
  {
    name: "ServiceWorkerRegistration",
    type: "class",
    status: "experimental",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration",
  },
  {
    name: "SyncEvent",
    type: "class",
    status: "nonstandard",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SyncEvent",
  },
  {
    name: "SyncManager",
    type: "class",
    status: "nonstandard",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/SyncManager",
  },
  {
    name: "WindowClient",
    type: "class",
    status: "experimental",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/WindowClient",
  },
];
