const standrad = [
  {
    name: "WebGLRenderingContext",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext",
  },
  {
    name: "WebGL2RenderingContext",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/WebGL2RenderingContext",
  },
  {
    name: "WebGLActiveInfo",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/WebGLActiveInfo",
  },
  {
    name: "WebGLBuffer",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/WebGLBuffer",
  },
  {
    name: "WebGLContextEvent",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/WebGLContextEvent",
  },
  {
    name: "WebGLFramebuffer",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/WebGLFramebuffer",
  },
  {
    name: "WebGLProgram",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/WebGLProgram",
  },
  {
    name: "WebGLQuery",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/WebGLQuery",
  },
  {
    name: "WebGLRenderbuffer",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderbuffer",
  },
  {
    name: "WebGLSampler",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/WebGLSampler",
  },
  {
    name: "WebGLShader",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/WebGLShader",
  },
  {
    name: "WebGLShaderPrecisionFormat",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/WebGLShaderPrecisionFormat",
  },
  {
    name: "WebGLSync",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/WebGLSync",
  },
  {
    name: "WebGLTexture",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/WebGLTexture",
  },
  {
    name: "WebGLTransformFeedback",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/WebGLTransformFeedback",
  },
  {
    name: "WebGLUniformLocation",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/WebGLUniformLocation",
  },
  {
    name: "WebGLVertexArrayObject",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/WebGLVertexArrayObject",
  },
];
const extension = [
  {
    name: "ANGLE_instanced_arrays",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/ANGLE_instanced_arrays",
  },
  {
    name: "EXT_blend_minmax",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/EXT_blend_minmax",
  },
  {
    name: "EXT_color_buffer_float",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/EXT_color_buffer_float",
  },
  {
    name: "EXT_color_buffer_half_float",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/EXT_color_buffer_half_float",
  },
  {
    name: "EXT_disjoint_timer_query",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/EXT_disjoint_timer_query",
  },
  {
    name: "EXT_float_blend",
    type: "class",
    status: "experimental",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/EXT_float_blend",
  },
  {
    name: "EXT_frag_depth",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/EXT_frag_depth",
  },
  {
    name: "EXT_shader_texture_lod",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/EXT_shader_texture_lod",
  },
  {
    name: "EXT_sRGB",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/EXT_sRGB",
  },
  {
    name: "EXT_texture_compression_bptc",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/EXT_texture_compression_bptc",
  },
  {
    name: "EXT_texture_compression_rgtc",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/EXT_texture_compression_rgtc",
  },
  {
    name: "EXT_texture_filter_anisotropic",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/EXT_texture_filter_anisotropic",
  },
  {
    name: "EXT_texture_norm16",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/EXT_texture_norm16",
  },
  {
    name: "KHR_parallel_shader_compile",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/KHR_parallel_shader_compile",
  },
  {
    name: "OES_element_index_uint",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/OES_element_index_uint",
  },
  {
    name: "OES_fbo_render_mipmap",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/OES_fbo_render_mipmap",
  },
  {
    name: "OES_standard_derivatives",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/OES_standard_derivatives",
  },
  {
    name: "OES_texture_float",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/OES_texture_float",
  },
  {
    name: "OES_texture_float_linear",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/OES_texture_float_linear",
  },
  {
    name: "OES_texture_half_float",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/OES_texture_half_float",
  },
  {
    name: "OES_texture_half_float_linear",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/OES_texture_half_float_linear",
  },
  {
    name: "OES_vertex_array_object",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/OES_vertex_array_object",
  },
  {
    name: "OVR_multiview2",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/OVR_multiview2",
  },
  {
    name: "WEBGL_color_buffer_float",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/WEBGL_color_buffer_float",
  },
  {
    name: "WEBGL_compressed_texture_astc",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/WEBGL_compressed_texture_astc",
  },
  {
    name: "WEBGL_compressed_texture_etc",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/WEBGL_compressed_texture_etc",
  },
  {
    name: "WEBGL_compressed_texture_etc1",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/WEBGL_compressed_texture_etc1",
  },
  {
    name: "WEBGL_compressed_texture_pvrtc",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/WEBGL_compressed_texture_pvrtc",
  },
  {
    name: "WEBGL_compressed_texture_s3tc",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/WEBGL_compressed_texture_s3tc",
  },
  {
    name: "WEBGL_compressed_texture_s3tc_srgb",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/WEBGL_compressed_texture_s3tc_srgb",
  },
  {
    name: "WEBGL_debug_renderer_info",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/WEBGL_debug_renderer_info",
  },
  {
    name: "WEBGL_debug_shaders",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/WEBGL_debug_shaders",
  },
  {
    name: "WEBGL_depth_texture",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/WEBGL_depth_texture",
  },
  {
    name: "WEBGL_draw_buffers",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/WEBGL_draw_buffers",
  },
  {
    name: "WEBGL_lose_context",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/WEBGL_lose_context",
  },
  {
    name: "WEBGL_multi_draw",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/WEBGL_multi_draw",
  },
];
const event = [
  {
    name: "webglcontextlost",
    type: "property",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/webglcontextlost_event",
  },
  {
    name: "webglcontextrestored",
    type: "property",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/webglcontextrestored_event",
  },
  {
    name: "webglcontextcreationerror",
    type: "property",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/webglcontextcreationerror_event",
  },
];

export const WebGL = [...standrad, ...extension, ...event];
