export const WebRTC = [
  {
    name: "RTCPeerConnection",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection",
  },
  {
    name: "RTCDataChannel",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/RTCDataChannel",
  },
  {
    name: "RTCDataChannelEvent",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/RTCDataChannelEvent",
  },
  {
    name: "RTCSessionDescription",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/RTCSessionDescription",
  },
  {
    name: "RTCStatsReport",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/RTCStatsReport",
  },
  {
    name: "RTCIceCandidate",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/RTCIceCandidate",
  },
  {
    name: "RTCIceTransport",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/RTCIceTransport",
  },
  {
    name: "RTCPeerConnectionIceEvent",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnectionIceEvent",
  },
  {
    name: "RTCRtpSender",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpSender",
  },
  {
    name: "RTCRtpReceiver",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpReceiver",
  },
  {
    name: "RTCTrackEvent",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/RTCTrackEvent",
  },
  {
    name: "RTCSctpTransport",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/RTCSctpTransport",
  },
  {
    name: "RTCIceServer",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/RTCIceServer",
  },
  {
    name: "RTCRtpContributingSource",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpContributingSource",
  },
  {
    name: "RTCIdentityProvider",
    type: "class",
    status: "normal",
    href: "",
  },
  {
    name: "RTCIdentityAssertion",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/RTCIdentityAssertion",
  },
  {
    name: "RTCIdentityProviderRegistrar",
    type: "class",
    status: "normal",
    href: "",
  },
  {
    name: "RTCCertificate",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/RTCCertificate",
  },
  {
    name: "RTCRtpTransceiver",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/RTCCertificate",
  },
  {
    name: "RTCEncodedVideoFrame",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/RTCCertificate",
  },
  {
    name: "RTCEncodedAudioFrame",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/RTCCertificate",
  },
  {
    name: "RTCDtlsTransport",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/RTCCertificate",
  },
  {
    name: "RTCDTMFSender",
    type: "class",
    status: "normal",
    href: "https://developer.mozilla.org/en-US/docs/Web/API/RTCCertificate",
  },
];
